name: spatialzoomer
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pyarrow
  - pandas
  - h5py
  - igraph
  - leidenalg
  - jupyterlab
  - pip:
      - setuptools<82
      - spatialzoomer==1.0.0
      - --extra-index-url https://download.pytorch.org/whl/cpu
      - torch
      - torchvision
